### ISSUE TITLE
Trouble Integration Testing

### ISSUE THREAD

**Issue by flexyford** [truecoach/ember-fit-form#20]
Consuming applications and addons do not benefit from the application initializer when running integration tests. We need an easy to use solution for consuming apps to test with ember-fit-form

**Comment by flexyford** [comment]
Something like this might do the trick. @jfdnc can you test something like this in our integration tests when you get a chance?

```js
import config from '../config/environment';
import { getOwner } from '@ember/application';

const { emberFitForm = {} } = config;
const { adapter = 'ember-changeset' } = emberFitForm;
const owner = getOwner(this) || this.owner;
owner.register('config:fit-form-adapter', adapter, { instantiate: false });
owner.inject('component:fit-form', 'adapter', 'config:fit-form-adapter');
```

**Comment by steveszc** [comment]
The initializer was removed in 3.x. Closing.
